- name: Install packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  changed_when: true
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.name }}"
  notify: on_complete
