jobs:
  create-tags:
    name: Tag the latest image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "AMI_ID=$(jq -r '.builds[-1].artifact_id | split(":")[1]' docs/packer-manifest.json)" >> $GITHUB_ENV
      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: |
          aws ec2 create-tags --resources $AMI_ID --tags Key=Release,Value=${{ github.event.release.tag_name }}
name: Create tags
"on":
  release:
    types:
      - published
