jobs:
  build:
    name: Build Amazon Machine Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        run: packer build -var="release=$GITHUB_REF" -var="skip_create_ami=false" template.json
name: Build Amazon Machine Image
"on":
  release:
    types:
      - created
