jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npx semantic-release
name: Release
"on":
  push:
    branches:
      - main
